In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'i am a good developer',
    'understand the meaning of words',
    'Your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'Your videos are good']

In [4]:
## define a vocabulary size

voc_size = 10000


In [5]:
# one hot representation for every word
one_hot_rep = [one_hot(words,voc_size) for words in sent]
one_hot_rep

[[1945, 315, 9067, 8100],
 [1945, 315, 9067, 4970],
 [1945, 4181, 9067, 2780],
 [5337, 6631, 3644, 6426, 6441],
 [5337, 6631, 3644, 6426, 5912],
 [9027, 1945, 2416, 9067, 7768],
 [3327, 9987, 2091, 6426]]

In [25]:
# word embedding representation

from tensorflow.keras.layers import Embedding, Input
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [26]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 1945,  315, 9067, 8100],
       [   0,    0,    0,    0, 1945,  315, 9067, 4970],
       [   0,    0,    0,    0, 1945, 4181, 9067, 2780],
       [   0,    0,    0, 5337, 6631, 3644, 6426, 6441],
       [   0,    0,    0, 5337, 6631, 3644, 6426, 5912],
       [   0,    0,    0, 9027, 1945, 2416, 9067, 7768],
       [   0,    0,    0,    0, 3327, 9987, 2091, 6426]], dtype=int32)

In [27]:
# feature representation
dim = 10

In [28]:
model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size,dim))
model.compile('adam',',mse')

In [29]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
embedded_docs

array([[   0,    0,    0,    0, 1945,  315, 9067, 8100],
       [   0,    0,    0,    0, 1945,  315, 9067, 4970],
       [   0,    0,    0,    0, 1945, 4181, 9067, 2780],
       [   0,    0,    0, 5337, 6631, 3644, 6426, 6441],
       [   0,    0,    0, 5337, 6631, 3644, 6426, 5912],
       [   0,    0,    0, 9027, 1945, 2416, 9067, 7768],
       [   0,    0,    0,    0, 3327, 9987, 2091, 6426]], dtype=int32)

In [31]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step


array([[[ 0.00487952, -0.00228264,  0.02302073, -0.03582466,
         -0.03697765, -0.0089653 ,  0.00179478, -0.04907259,
         -0.03800479, -0.00827587],
        [ 0.00487952, -0.00228264,  0.02302073, -0.03582466,
         -0.03697765, -0.0089653 ,  0.00179478, -0.04907259,
         -0.03800479, -0.00827587],
        [ 0.00487952, -0.00228264,  0.02302073, -0.03582466,
         -0.03697765, -0.0089653 ,  0.00179478, -0.04907259,
         -0.03800479, -0.00827587],
        [ 0.00487952, -0.00228264,  0.02302073, -0.03582466,
         -0.03697765, -0.0089653 ,  0.00179478, -0.04907259,
         -0.03800479, -0.00827587],
        [ 0.00338345, -0.03420717,  0.02429901,  0.03926376,
         -0.04692757,  0.03256733, -0.02321163,  0.03309717,
         -0.02749517,  0.04638768],
        [-0.01567926, -0.02261396,  0.00166406, -0.02505922,
          0.04125128,  0.01543686, -0.02220355, -0.03610344,
         -0.03492762,  0.04734727],
        [-0.03919528, -0.03836711,  0.01882683, -0.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')